#include <iostream>
using namespace std;

int main(int argc, char const *argv[])
{
    cout << "\
    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n\
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n\
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n\
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n\
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n\
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n\
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n\
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n\
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n\
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n\
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n\
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n\
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n\
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n\
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n\
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n\
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n\
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n\
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n\
" << endl;
    return 0;
}
